interactions:
	python3 interactions_from_video_n_cursorTracking.py gs://nova_assets/sample_videos/2July_Faircado_test_nova/register_with_email_happy_sad/screen_record_annotated.mp4 cursor_logs/extracted_clicks.json

track:
	python3 record_and_track.py
collate:
	python3 collate_tracking.py
