clean:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/cleaning.txt

# User onboarding
run1:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_1.txt
run2_1:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_2.1.txt
run2_2:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_2.2.txt
run2_3:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_2.3.txt
run2_4:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_2.4.txt
run2_5:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_2.5.txt
run2_55:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_2.55.txt
run2_6:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_2.6.txt
run2_7:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_2.7.txt
run2_75:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_2.75.txt
run2:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_2.txt
run3:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_3.txt
run3_5:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_3.5.txt
run4:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_4.txt
run5:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_5.txt
run6:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_6.txt
run7:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_7.txt
run8:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_8.txt
run9:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_9.txt
run10:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_10.txt
run11:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_11.txt
run12:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_12.txt
run13:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_13.txt
run14:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_1/path_11_execId_14.txt

# sign up account doesn't exist
feat3_path1_run1:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_3/path_1_execId_1.txt
feat3_path1_run2:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_3/path_1_execId_2.txt
feat3_path1_run3:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_3/path_1_execId_3.txt
feat3_path1_run4:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_3/path_1_execId_4.txt
feat3_path1_run5:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_3/path_1_execId_5.txt
feat3_path1_run6:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_3/path_1_execId_6.txt
feat3_path1_run7:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_3/path_1_execId_7.txt
feat3_path1_run8:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_3/path_1_execId_8.txt
feat3_path1_run9:
	python3 main.py ~/qai/local_codebase/computer/claude-computer-use-macos/algos/graph/path_prompts/feature_3/path_1_execId_9.txt
