gen:
	python3 create_graph.py 1
	python3 create_graph.py 2
	python3 create_graph.py 3
plot:
	python3 plot_graph.py 1
	python3 plot_graph.py 2
	python3 plot_graph.py 3
dfs:
	python3 dfs_path_prompt_gen.py 1
	python3 dfs_path_prompt_gen.py 2
	python3 dfs_path_prompt_gen.py 3
clean:
	rm -rf adj_lists
	rm -rf path_prompts/feature_*
	rm -rf plots
