#!/bin/bash

if [[ -z "$ENVIRONMENT" || -z "$GCP_PROJECT_ID_STAGING" ]]; then
    echo "Error: ENVIRONMENT or GCP_PROJECT_ID_STAGING is not set as an environment variable"
    exit 1
fi

if [[ -z "$1" || -z "$2" ]]; then
    echo "Usage: $0 <function_name> <entry_point> [memory] [timeout]"
    exit 1
fi

FUNCTION_NAME="$1"
ENTRY_POINT="$2"
MEMORY="${3:-2GB}"
TIMEOUT="${4:-60s}"
CONCURRENCY="${5:-10}"
MIN_INSTANCES="${6:-0}"

REGION="europe-west3"

echo "Deploying $FUNCTION_NAME to project: $GCP_PROJECT_ID_STAGING"

ENV_VARS="ENVIRONMENT=$ENVIRONMENT,\
PATH_TO_GCP_CREDS_STAGING=$PATH_TO_GCP_CREDS_STAGING,\
REMOVED=$REMOVED,\
CLERK_JWKS_URL_STAGING=$CLERK_JWKS_URL_STAGING,\
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY_STAGING=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY_STAGING,\
CLERK_SECRET_KEY_STAGING=$CLERK_SECRET_KEY_STAGING,\
HMAC_SECRET_KEY_STAGING=$HMAC_SECRET_KEY_STAGING,\
GCP_PROJECT_ID_STAGING=$GCP_PROJECT_ID_STAGING,\
NOTIFICATION_WEBHOOK_URL=$NOTIFICATION_WEBHOOK_URL,\
TEST_RUN_UPDATE_WEBHOOK_URL=$TEST_RUN_UPDATE_WEBHOOK_URL,\
CUSTOMER_COMMENTS_WEBHOOK_URL=$CUSTOMER_COMMENTS_WEBHOOK_URL,\
SENTRY_DSN_URL=$SENTRY_DSN_URL,\
ENABLE_SHARDING_FOR_KG_FLOW_ANALYZER=$ENABLE_SHARDING_FOR_KG_FLOW_ANALYZER,\
TCS_FROM_FLOW_TIMEOUT_MINS=$TCS_FROM_FLOW_TIMEOUT_MINS,\
ENABLE_NEW_VIDEO_TO_FLOW=$ENABLE_NEW_VIDEO_TO_FLOW,\
MIXPANEL_TOKEN_STAGING=$MIXPANEL_TOKEN_STAGING,\
JIRA_ENCRYPTION_KEY=$JIRA_ENCRYPTION_KEY,\
STRIPE_SECRET_KEY_STAGING=$STRIPE_SECRET_KEY_STAGING,\
REMOVED=$REMOVED"

gcloud functions deploy "$FUNCTION_NAME" \
    --entry-point "$ENTRY_POINT" \
    --runtime python312 \
    --memory "$MEMORY" \
    --trigger-http \
    --allow-unauthenticated \
    --source ./src \
    --region "$REGION" \
    --set-env-vars "$ENV_VARS" \
    --set-secrets PATH_TO_GMAIL_CREDS_STAGING=gmail-service-account:latest \
    --timeout "$TIMEOUT" \
    --concurrency "$CONCURRENCY" \
    --min-instances "$MIN_INSTANCES" \
    --project="$GCP_PROJECT_ID_STAGING"

