[mypy]
python_version = 3.11
check_untyped_defs = True
exclude = ^(venv|.*_build|.*site-packages|fixup_pubsub_v1_keywords.py)$

[mypy-google.*]
ignore_missing_imports = True

[mypy-google.generativeai.*]
ignore_missing_imports = True

[mypy-flask_swagger_ui.*]
ignore_missing_imports = True

[mypy-vertexai.*]
ignore_missing_imports = True

[mypy-setuptools]
ignore_missing_imports = True

[mypy-libcst]
ignore_missing_imports = True

[mypy-moviepy.*]
ignore_missing_imports = True

[mypy-instructor]
ignore_missing_imports = True

[mypy-instructor.*]
ignore_missing_imports = True

